import assert from 'node:assert/strict';
import { createCalculiXElectrostaticSlabDeck, recoverCalculiXElectrostaticSlab } from '../providers/calculix/CalculiXElectrostaticSlab.mts';
import { parallelPlateElectrostaticReference } from '../simulation-bridge/electrostaticFoundation.mts';
import { digest } from '../simulation-bridge/stableDigest.mts';
import { slabRequest, syntheticSlabMesh, syntheticElectricalDat } from './sim9-electrostatic-fixture.mts';

const request = slabRequest(); const mesh = syntheticSlabMesh(); const dat = syntheticElectricalDat(mesh);
const deck = createCalculiXElectrostaticSlabDeck(request, mesh);
assert.deepEqual(createCalculiXElectrostaticSlabDeck(request, mesh), deck);
assert.match(deck.deck, /\*HEAT TRANSFER, STEADY STATE/);
assert.match(deck.deck, /\*CONDUCTIVITY\n1\n/);
assert.doesNotMatch(deck.deck, /\*DFLUX|\*ELASTIC|\*STATIC/);
const result = recoverCalculiXElectrostaticSlab(request, mesh, dat);
assert.deepEqual(recoverCalculiXElectrostaticSlab(request, mesh, dat), result);
const reference = parallelPlateElectrostaticReference(request);
assert.ok(Math.abs(result.capacitanceF - reference.capacitanceF) < 1e-24);
assert.ok(Math.abs(result.electrostaticEnergyJ - reference.electrostaticEnergyJ) < 1e-20);
result.samples.forEach((sample, index) => assert.ok(Math.abs(sample.electricPotentialV - reference.samples[index].electricPotentialV) < 1e-10));
assert.ok(result.electricFields.every(field => Math.abs(field.electricFieldMagnitudeVPerM - 100000) < 1e-6));
assert.ok(!/temperature|heat_flux|heatFlow|thermal/.test(JSON.stringify(result)));
const { resultDigest, ...unsigned } = result; assert.equal(resultDigest, digest(unsigned));
let rejects = 0;
function reject(label: string, altered: string) {
  assert.throws(() => recoverCalculiXElectrostaticSlab(request, mesh, altered), /ELECTROSTATIC_SLAB_INVALID/, label); rejects++;
}
reject('missing potential', dat.replace(/\n1 0\n/, '\n'));
reject('duplicate potential', dat.replace(/\n1 0\n/, '\n1 0\n1 0\n'));
reject('nonfinite potential', dat.replace(/\n1 0\n/, '\n1 NaN\n'));
reject('bad field', dat.replace('1 1 -100 0 0', '1 1 -50 0 0'));
reject('energy inconsistency within individual field tolerance', dat.replaceAll('-100 0 0', '-100.009 0 0'));
reject('hex numeric encoding', dat.replace(/\n1 0\n/, '\n0x1 0\n'));
reject('nonfinite field', dat.replace('1 1 -100 0 0', '1 1 Infinity 0 0'));
reject('missing integration point', dat.replace('1 1 -100 0 0\n', ''));
reject('duplicate integration point', dat.replace('1 1 -100 0 0', '1 1 -100 0 0\n1 1 -100 0 0'));
reject('invalid integration point', dat.replace('1 1 -100 0 0', '1 5 -100 0 0'));
reject('unknown electrode set', dat.replace('ELECTRODE_LEFT', 'ELECTRODE_UNKNOWN'));
reject('wrong potential set', dat.replace('NALL', 'OTHER'));
reject('wrong field set', dat.replace('EALL', 'OTHER'));
reject('wrong-face reaction nodes', dat.replaceAll('ELECTRODE_LEFT', 'SWAP')
  .replaceAll('ELECTRODE_RIGHT', 'ELECTRODE_LEFT').replaceAll('SWAP', 'ELECTRODE_RIGHT'));
reject('nonfinite electrode reaction', dat.replace(/(ELECTRODE_LEFT and time 1\n\d+ )[-\d.]+/, '$1NaN'));
reject('inconsistent electrode reaction', dat.replace(/(ELECTRODE_LEFT and time 1\n\d+ )[-\d.]+/, '$1-999999'));
reject('missing electrode', dat.replace(/ heat generation \(node,RFL\) for set ELECTRODE_RIGHT[\s\S]*?(?= heat flux)/, ''));
reject('incomplete frame', dat.replace('and time 1', 'and time 0.5'));
reject('duplicate frame', dat + dat);
reject('malformed field columns', dat.replace('1 1 -100 0 0', '1 1 -100 0'));
reject('silent garbage', dat + 'garbage\n');
reject('altered potential profile', dat.replace(/\n1 0\n/, '\n1 10\n'));
reject('unbounded output', ' '.repeat(8 * 1024 * 1024 + 1));
const wrongMesh = structuredClone(mesh);
wrongMesh.requestDigest = digest({ wrong: true });
assert.throws(() => createCalculiXElectrostaticSlabDeck(request, wrongMesh));
assert.throws(() => recoverCalculiXElectrostaticSlab(request, wrongMesh, dat)); rejects += 2;
const wrongFace = structuredClone(mesh);
wrongFace.boundaryRegions[0].facetIndices = [...mesh.boundaryRegions[1].facetIndices];
assert.throws(() => createCalculiXElectrostaticSlabDeck(request, wrongFace)); rejects++;
const missingOwner = structuredClone(mesh);
missingOwner.volumeRegions[0].elementIndices.pop();
assert.throws(() => createCalculiXElectrostaticSlabDeck(request, missingOwner)); rejects++;
console.log(JSON.stringify({ status: 'PASS', provenance: 'synthetic_parser_fixture_only', rejectedCases: rejects, solverExecutions: 0 }));
